// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	order "greet/internal/handler/order"
	pledge "greet/internal/handler/pledge"
	user "greet/internal/handler/user"
	"greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建订单
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				// 创建订单
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: order.OrderDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取token
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: pledge.GetTokenInfoHandler(serverCtx),
			},
			{
				// 获取TokenList
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: pledge.GetTokenInfoListHandler(serverCtx),
			},
			{
				// 获取TokenList
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: pledge.SearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/pledge"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建用户
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				// 获取用户
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: user.UserDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)
}
