// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBountyPaymentTerm = "bounty_payment_terms"

// BountyPaymentTerm mapped from table <bounty_payment_terms>
type BountyPaymentTerm struct {
	ID           int64     `gorm:"column:id;primaryKey" json:"id"`
	BountyID     int64     `gorm:"column:bounty_id;not null" json:"bounty_id"`
	PaymentMode  bool      `gorm:"column:payment_mode;not null" json:"payment_mode"`
	Token1Symbol string    `gorm:"column:token1_symbol;not null" json:"token1_symbol"`
	Token1Amount int32     `gorm:"column:token1_amount;not null" json:"token1_amount"`
	Token2Symbol string    `gorm:"column:token2_symbol;not null" json:"token2_symbol"`
	Token2Amount int32     `gorm:"column:token2_amount;not null" json:"token2_amount"`
	Terms        string    `gorm:"column:terms;not null" json:"terms"`
	SeqNum       int32     `gorm:"column:seq_num;not null" json:"seq_num"`
	Status       int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted    bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName BountyPaymentTerm's table name
func (*BountyPaymentTerm) TableName() string {
	return TableNameBountyPaymentTerm
}
