// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBountyPaymentPeriod = "bounty_payment_period"

// BountyPaymentPeriod mapped from table <bounty_payment_period>
type BountyPaymentPeriod struct {
	ID           int64     `gorm:"column:id;primaryKey" json:"id"`
	BountyID     int64     `gorm:"column:bounty_id;not null" json:"bounty_id"`
	PeriodType   bool      `gorm:"column:period_type;not null" json:"period_type"`
	PeriodAmount int64     `gorm:"column:period_amount;not null" json:"period_amount"`
	HoursPerDay  int32     `gorm:"column:hours_per_day;not null" json:"hours_per_day"`
	Token1Symbol string    `gorm:"column:token1_symbol;not null" json:"token1_symbol"`
	Token1Amount int32     `gorm:"column:token1_amount;not null" json:"token1_amount"`
	Token2Symbol string    `gorm:"column:token2_symbol;not null" json:"token2_symbol"`
	Token2Amount int32     `gorm:"column:token2_amount;not null" json:"token2_amount"`
	Target       string    `gorm:"column:target;not null" json:"target"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted    bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName BountyPaymentPeriod's table name
func (*BountyPaymentPeriod) TableName() string {
	return TableNameBountyPaymentPeriod
}
