// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBounty = "bounty"

// Bounty mapped from table <bounty>
type Bounty struct {
	ID                 int64     `gorm:"column:id;primaryKey" json:"id"`
	ChainID            int64     `gorm:"column:chain_id;not null;comment:Chain ID" json:"chain_id"`                         // Chain ID
	TxHash             string    `gorm:"column:tx_hash;not null;comment:Transcation Hash" json:"tx_hash"`                   // Transcation Hash
	DepositContract    string    `gorm:"column:deposit_contract;not null;comment:Contract Address" json:"deposit_contract"` // Contract Address
	StartupID          int64     `gorm:"column:startup_id;not null" json:"startup_id"`
	ComerID            int64     `gorm:"column:comer_id;not null" json:"comer_id"`
	Title              string    `gorm:"column:title;not null" json:"title"`
	ApplyCutoffDate    time.Time `gorm:"column:apply_cutoff_date;not null;default:CURRENT_TIMESTAMP" json:"apply_cutoff_date"`
	DiscussionLink     string    `gorm:"column:discussion_link;not null" json:"discussion_link"`
	DepositTokenSymbol string    `gorm:"column:deposit_token_symbol;not null" json:"deposit_token_symbol"`
	ApplicantDeposit   int32     `gorm:"column:applicant_deposit;not null" json:"applicant_deposit"`
	FounderDeposit     int32     `gorm:"column:founder_deposit;not null" json:"founder_deposit"`
	Description        string    `gorm:"column:description;not null" json:"description"`
	PaymentMode        int32     `gorm:"column:payment_mode;not null" json:"payment_mode"`
	Status             bool      `gorm:"column:status;not null" json:"status"`
	TotalRewardToken   int32     `gorm:"column:total_reward_token;not null" json:"total_reward_token"`
	CreatedAt          time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted          bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName Bounty's table name
func (*Bounty) TableName() string {
	return TableNameBounty
}
