// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBountyDeposit = "bounty_deposit"

// BountyDeposit mapped from table <bounty_deposit>
type BountyDeposit struct {
	ID          int64     `gorm:"column:id;primaryKey" json:"id"`
	ChainID     int64     `gorm:"column:chain_id;not null" json:"chain_id"`
	TxHash      string    `gorm:"column:tx_hash;not null" json:"tx_hash"`
	Status      bool      `gorm:"column:status;not null" json:"status"`
	BountyID    int64     `gorm:"column:bounty_id;not null" json:"bounty_id"`
	ComerID     int64     `gorm:"column:comer_id;not null" json:"comer_id"`
	Access      int32     `gorm:"column:access;not null" json:"access"`
	TokenSymbol string    `gorm:"column:token_symbol;not null" json:"token_symbol"`
	TokenAmount int32     `gorm:"column:token_amount;not null" json:"token_amount"`
	Timestamp   time.Time `gorm:"column:timestamp;not null;default:0000-00-00 00:00:00" json:"timestamp"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted   bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName BountyDeposit's table name
func (*BountyDeposit) TableName() string {
	return TableNameBountyDeposit
}
