// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChain = "chain"

// Chain mapped from table <chain>
type Chain struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	ChainID   int64     `gorm:"column:chain_id;not null;comment:Chain ID" json:"chain_id"`                  // Chain ID
	Name      string    `gorm:"column:name;not null;comment:Chain name" json:"name"`                        // Chain name
	Logo      string    `gorm:"column:logo;not null;comment:Chain logo" json:"logo"`                        // Chain logo
	Status    bool      `gorm:"column:status;not null;default:1;comment:1-normal, 2-disable" json:"status"` // 1-normal, 2-disable
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null;comment:Is deleted" json:"is_deleted"` // Is deleted
}

// TableName Chain's table name
func (*Chain) TableName() string {
	return TableNameChain
}
