// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChainEndpoint = "chain_endpoint"

// ChainEndpoint mapped from table <chain_endpoint>
type ChainEndpoint struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	Protocol  bool      `gorm:"column:protocol;not null;comment:Communication protocol, 1-rpc 2-wss" json:"protocol"` // Communication protocol, 1-rpc 2-wss
	ChainID   int64     `gorm:"column:chain_id;not null;comment:Chain ID" json:"chain_id"`                            // Chain ID
	URL       string    `gorm:"column:url;not null;comment:Chain name" json:"url"`                                    // Chain name
	Status    bool      `gorm:"column:status;not null;default:1;comment:1-normal, 2-disable" json:"status"`           // 1-normal, 2-disable
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null;comment:Is deleted" json:"is_deleted"` // Is deleted
}

// TableName ChainEndpoint's table name
func (*ChainEndpoint) TableName() string {
	return TableNameChainEndpoint
}
