// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComerFollowRel = "comer_follow_rel"

// ComerFollowRel mapped from table <comer_follow_rel>
type ComerFollowRel struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ComerID       int64     `gorm:"column:comer_id;not null" json:"comer_id"`
	TargetComerID int64     `gorm:"column:target_comer_id;not null" json:"target_comer_id"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted     bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName ComerFollowRel's table name
func (*ComerFollowRel) TableName() string {
	return TableNameComerFollowRel
}
