// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComerAccount = "comer_account"

// ComerAccount mapped from table <comer_account>
type ComerAccount struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	ComerID   int64     `gorm:"column:comer_id;not null;comment:comer unique identifier" json:"comer_id"`                                                         // comer unique identifier
	Oin       string    `gorm:"column:oin;not null;comment:comer outer account unique identifier, wallet will be public key and Oauth is the OauthID" json:"oin"` // comer outer account unique identifier, wallet will be public key and Oauth is the OauthID
	IsPrimary bool      `gorm:"column:is_primary;not null;comment:comer use this account as primay account" json:"is_primary"`                                    // comer use this account as primay account
	Nick      string    `gorm:"column:nick;not null;comment:comer nick name" json:"nick"`                                                                         // comer nick name
	Avatar    string    `gorm:"column:avatar;not null;comment:avatar link address" json:"avatar"`                                                                 // avatar link address
	Type      int32     `gorm:"column:type;not null;comment:1 for github  2 for google 3 for twitter 4 for facebook 5 for likedin" json:"type"`                   // 1 for github  2 for google 3 for twitter 4 for facebook 5 for likedin
	IsLinked  bool      `gorm:"column:is_linked;not null;comment:0 for unlink 1 for linked" json:"is_linked"`                                                     // 0 for unlink 1 for linked
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null;comment:Is Deleted" json:"is_deleted"` // Is Deleted
}

// TableName ComerAccount's table name
func (*ComerAccount) TableName() string {
	return TableNameComerAccount
}
