// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComerSocial = "comer_social"

// ComerSocial mapped from table <comer_social>
type ComerSocial struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ComerID    int64     `gorm:"column:comer_id;not null;comment:用户ID" json:"comer_id"`                          // 用户ID
	Platform   string    `gorm:"column:platform;not null;comment:平台(twitter/discord/telegram等)" json:"platform"` // 平台(twitter/discord/telegram等)
	Username   string    `gorm:"column:username;not null;comment:用户名" json:"username"`                           // 用户名
	URL        string    `gorm:"column:url;not null;comment:链接" json:"url"`                                      // 链接
	IsVerified bool      `gorm:"column:is_verified;not null;comment:是否认证" json:"is_verified"`                    // 是否认证
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted  bool      `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"` // 是否删除
}

// TableName ComerSocial's table name
func (*ComerSocial) TableName() string {
	return TableNameComerSocial
}
