// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComer = "comer"

// Comer mapped from table <comer>
type Comer struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	Address   string    `gorm:"column:address;not null;comment:comer could save some useful info on block chain with this address" json:"address"` // comer could save some useful info on block chain with this address
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null;comment:Is Deleted" json:"is_deleted"` // Is Deleted
}

// TableName Comer's table name
func (*Comer) TableName() string {
	return TableNameComer
}
