// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComerLanguage = "comer_language"

// ComerLanguage mapped from table <comer_language>
type ComerLanguage struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ComerID   int64     `gorm:"column:comer_id;not null;comment:用户ID" json:"comer_id"`   // 用户ID
	Language  string    `gorm:"column:language;not null;comment:语言" json:"language"`     // 语言
	Code      string    `gorm:"column:code;not null;comment:语言代码" json:"code"`           // 语言代码
	Level     int32     `gorm:"column:level;not null;comment:熟练度(1-5)" json:"level"`     // 熟练度(1-5)
	IsNative  bool      `gorm:"column:is_native;not null;comment:是否母语" json:"is_native"` // 是否母语
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"` // 是否删除
}

// TableName ComerLanguage's table name
func (*ComerLanguage) TableName() string {
	return TableNameComerLanguage
}
