// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComerSkill = "comer_skill"

// ComerSkill mapped from table <comer_skill>
type ComerSkill struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ComerID     int64     `gorm:"column:comer_id;not null;comment:用户ID" json:"comer_id"`     // 用户ID
	SkillName   string    `gorm:"column:skill_name;not null;comment:技能名称" json:"skill_name"` // 技能名称
	Level       int32     `gorm:"column:level;not null;comment:熟练度(1-5)" json:"level"`       // 熟练度(1-5)
	Years       int32     `gorm:"column:years;not null;comment:使用年限" json:"years"`           // 使用年限
	Description string    `gorm:"column:description;not null;comment:描述" json:"description"` // 描述
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted   bool      `gorm:"column:is_deleted;not null;comment:是否删除" json:"is_deleted"` // 是否删除
}

// TableName ComerSkill's table name
func (*ComerSkill) TableName() string {
	return TableNameComerSkill
}
