// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComerProfile = "comer_profile"

// ComerProfile mapped from table <comer_profile>
type ComerProfile struct {
	ID         int64     `gorm:"column:id;primaryKey" json:"id"`
	ComerID    int64     `gorm:"column:comer_id;not null" json:"comer_id"`
	Name       string    `gorm:"column:name;not null;comment:name" json:"name"`       // name
	Avatar     string    `gorm:"column:avatar;not null;comment:avatar" json:"avatar"` // avatar
	Cover      string    `gorm:"column:cover;not null" json:"cover"`
	Location   string    `gorm:"column:location;not null;comment:location city" json:"location"`          // location city
	TimeZone   string    `gorm:"column:time_zone;not null;comment:time zone: UTC-09:30" json:"time_zone"` // time zone: UTC-09:30
	Website    string    `gorm:"column:website;not null;comment:website" json:"website"`                  // website
	Email      string    `gorm:"column:email;not null;comment:email" json:"email"`                        // email
	Twitter    string    `gorm:"column:twitter;not null;comment:twitter" json:"twitter"`                  // twitter
	Discord    string    `gorm:"column:discord;not null;comment:discord" json:"discord"`                  // discord
	Telegram   string    `gorm:"column:telegram;not null;comment:telegram" json:"telegram"`               // telegram
	Medium     string    `gorm:"column:medium;not null;comment:medium" json:"medium"`                     // medium
	Facebook   string    `gorm:"column:facebook;not null" json:"facebook"`
	Linktree   string    `gorm:"column:linktree;not null" json:"linktree"`
	Bio        string    `gorm:"column:bio;not null;comment:bio" json:"bio"` // bio
	Languages  string    `gorm:"column:languages;not null" json:"languages"`
	Educations string    `gorm:"column:educations;not null" json:"educations"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted  bool      `gorm:"column:is_deleted;not null;comment:Is Deleted" json:"is_deleted"` // Is Deleted
}

// TableName ComerProfile's table name
func (*ComerProfile) TableName() string {
	return TableNameComerProfile
}
