// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCrowdfunding = "crowdfunding"

// Crowdfunding mapped from table <crowdfunding>
type Crowdfunding struct {
	ID                   int64     `gorm:"column:id;primaryKey;comment:crowdfunding id" json:"id"`                                                                  // crowdfunding id
	ChainID              int64     `gorm:"column:chain_id;not null;comment:Chain id" json:"chain_id"`                                                               // Chain id
	TxHash               string    `gorm:"column:tx_hash;not null;comment:Tx hash" json:"tx_hash"`                                                                  // Tx hash
	CrowdfundingContract string    `gorm:"column:crowdfunding_contract;not null;comment:Crowdfunding contract address" json:"crowdfunding_contract"`                // Crowdfunding contract address
	StartupID            int64     `gorm:"column:startup_id;not null;comment:Startup id" json:"startup_id"`                                                         // Startup id
	ComerID              int64     `gorm:"column:comer_id;not null;comment:Founder's comer id" json:"comer_id"`                                                     // Founder's comer id
	RaiseGoal            float64   `gorm:"column:raise_goal;not null;default:0.000000000000000000;comment:Raise goal total" json:"raise_goal"`                      // Raise goal total
	RaiseBalance         float64   `gorm:"column:raise_balance;not null;default:0.000000000000000000;comment:Raise token balance" json:"raise_balance"`             // Raise token balance
	SellTokenContract    string    `gorm:"column:sell_token_contract;not null;comment:Sell token contract address" json:"sell_token_contract"`                      // Sell token contract address
	SellTokenName        string    `gorm:"column:sell_token_name;not null;comment:Sell token name" json:"sell_token_name"`                                          // Sell token name
	SellTokenSymbol      string    `gorm:"column:sell_token_symbol;not null;comment:Sell token symbol" json:"sell_token_symbol"`                                    // Sell token symbol
	SellTokenDecimals    int32     `gorm:"column:sell_token_decimals;not null;comment:Sell token decimals" json:"sell_token_decimals"`                              // Sell token decimals
	SellTokenSupply      float64   `gorm:"column:sell_token_supply;not null;default:0.000000000000000000;comment:Sell token total supply" json:"sell_token_supply"` // Sell token total supply
	SellTokenDeposit     float64   `gorm:"column:sell_token_deposit;not null;default:0.000000000000000000;comment:Sell token deposit" json:"sell_token_deposit"`    // Sell token deposit
	SellTokenBalance     float64   `gorm:"column:sell_token_balance;not null;default:0.000000000000000000;comment:Sell token balance" json:"sell_token_balance"`    // Sell token balance
	BuyTokenContract     string    `gorm:"column:buy_token_contract;not null;comment:Buy token contract address" json:"buy_token_contract"`                         // Buy token contract address
	BuyTokenName         string    `gorm:"column:buy_token_name;not null;comment:Buy token name" json:"buy_token_name"`                                             // Buy token name
	BuyTokenSymbol       string    `gorm:"column:buy_token_symbol;not null;comment:Buy token symbol" json:"buy_token_symbol"`                                       // Buy token symbol
	BuyTokenDecimals     int32     `gorm:"column:buy_token_decimals;not null;comment:Buy token decimals" json:"buy_token_decimals"`                                 // Buy token decimals
	BuyTokenSupply       float64   `gorm:"column:buy_token_supply;not null;default:0.000000000000000000;comment:Buy token total supply" json:"buy_token_supply"`    // Buy token total supply
	TeamWallet           string    `gorm:"column:team_wallet;not null;comment:Team wallet address" json:"team_wallet"`                                              // Team wallet address
	SwapPercent          float32   `gorm:"column:swap_percent;not null;comment:Swap percent" json:"swap_percent"`                                                   // Swap percent
	BuyPrice             float64   `gorm:"column:buy_price;not null;default:0.000000000000000000;comment:IBO rate" json:"buy_price"`                                // IBO rate
	MaxBuyAmount         float64   `gorm:"column:max_buy_amount;not null;default:0.000000000000000000;comment:Maximum buy amount" json:"max_buy_amount"`            // Maximum buy amount
	MaxSellPercent       float32   `gorm:"column:max_sell_percent;not null;comment:Maximum selling percent" json:"max_sell_percent"`                                // Maximum selling percent
	SellTax              float32   `gorm:"column:sell_tax;not null;comment:Selling tax" json:"sell_tax"`                                                            // Selling tax
	StartTime            time.Time `gorm:"column:start_time;not null;default:0000-00-00 00:00:00;comment:Start time" json:"start_time"`                             // Start time
	EndTime              time.Time `gorm:"column:end_time;not null;default:0000-00-00 00:00:00;comment:End time" json:"end_time"`                                   // End time
	Poster               string    `gorm:"column:poster;not null;comment:Poster url" json:"poster"`                                                                 // Poster url
	Youtube              string    `gorm:"column:youtube;not null;comment:Youtube link" json:"youtube"`                                                             // Youtube link
	Detail               string    `gorm:"column:detail;not null;comment:Detail url" json:"detail"`                                                                 // Detail url
	Description          string    `gorm:"column:description;not null;comment:Description content" json:"description"`                                              // Description content
	Status               bool      `gorm:"column:status;not null;comment:0:Pending 1:Upcoming 2:Live 3:Ended 4:Cancelled 5:Failure" json:"status"`                  // 0:Pending 1:Upcoming 2:Live 3:Ended 4:Cancelled 5:Failure
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted            bool      `gorm:"column:is_deleted;not null;comment:Is deleted" json:"is_deleted"` // Is deleted
}

// TableName Crowdfunding's table name
func (*Crowdfunding) TableName() string {
	return TableNameCrowdfunding
}
