// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCrowdfundingSwap = "crowdfunding_swap"

// CrowdfundingSwap mapped from table <crowdfunding_swap>
type CrowdfundingSwap struct {
	ID              int64     `gorm:"column:id;primaryKey" json:"id"`
	ChainID         int64     `gorm:"column:chain_id;not null;comment:Chain id" json:"chain_id"` // Chain id
	TxHash          string    `gorm:"column:tx_hash;not null;comment:Tx hash" json:"tx_hash"`    // Tx hash
	Timestamp       time.Time `gorm:"column:timestamp;not null;default:0000-00-00 00:00:00" json:"timestamp"`
	Status          bool      `gorm:"column:status;not null;comment:0:Pending 1:Success 2:Failure" json:"status"`                                           // 0:Pending 1:Success 2:Failure
	CrowdfundingID  int64     `gorm:"column:crowdfunding_id;not null;comment:Crowdfunding id" json:"crowdfunding_id"`                                       // Crowdfunding id
	ComerID         int64     `gorm:"column:comer_id;not null;comment:Comer id" json:"comer_id"`                                                            // Comer id
	Access          bool      `gorm:"column:access;not null;comment:1:Invest 2:Withdraw" json:"access"`                                                     // 1:Invest 2:Withdraw
	BuyTokenSymbol  string    `gorm:"column:buy_token_symbol;not null;comment:Buy token symbol" json:"buy_token_symbol"`                                    // Buy token symbol
	BuyTokenAmount  float64   `gorm:"column:buy_token_amount;not null;default:0.000000000000000000;comment:Buy token amount" json:"buy_token_amount"`       // Buy token amount
	SellTokenSymbol string    `gorm:"column:sell_token_symbol;not null;comment:Selling token symbol" json:"sell_token_symbol"`                              // Selling token symbol
	SellTokenAmount float64   `gorm:"column:sell_token_amount;not null;default:0.000000000000000000;comment:Selling token amount" json:"sell_token_amount"` // Selling token amount
	Price           float64   `gorm:"column:price;not null;default:0.000000000000000000;comment:Swap price" json:"price"`                                   // Swap price
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName CrowdfundingSwap's table name
func (*CrowdfundingSwap) TableName() string {
	return TableNameCrowdfundingSwap
}
