// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCrowdfundingIboRate = "crowdfunding_ibo_rate"

// CrowdfundingIboRate mapped from table <crowdfunding_ibo_rate>
type CrowdfundingIboRate struct {
	ID             int64     `gorm:"column:id;primaryKey" json:"id"`
	CrowdfundingID int64     `gorm:"column:crowdfunding_id;not null;comment:Crowdfunding id" json:"crowdfunding_id"`                               // Crowdfunding id
	EndTime        time.Time `gorm:"column:end_time;not null;default:0000-00-00 00:00:00;comment:End time" json:"end_time"`                        // End time
	MaxBuyAmount   float64   `gorm:"column:max_buy_amount;not null;default:0.000000000000000000;comment:Maximum buy amount" json:"max_buy_amount"` // Maximum buy amount
	MaxSellPercent float32   `gorm:"column:max_sell_percent;not null;comment:Maximum sell percent" json:"max_sell_percent"`                        // Maximum sell percent
	BuyPrice       float64   `gorm:"column:buy_price;not null;default:0.000000000000000000;comment:IBO rate" json:"buy_price"`                     // IBO rate
	SwapPercent    float32   `gorm:"column:swap_percent;not null;comment:Swap percent" json:"swap_percent"`                                        // Swap percent
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName CrowdfundingIboRate's table name
func (*CrowdfundingIboRate) TableName() string {
	return TableNameCrowdfundingIboRate
}
