// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDictDatum = "dict_data"

// DictDatum mapped from table <dict_data>
type DictDatum struct {
	ID        int32     `gorm:"column:id;primaryKey" json:"id"`
	StartupID int64     `gorm:"column:startup_id;not null" json:"startup_id"`
	DictType  string    `gorm:"column:dict_type;not null" json:"dict_type"`
	DictLabel string    `gorm:"column:dict_label;not null" json:"dict_label"`
	DictValue string    `gorm:"column:dict_value;not null" json:"dict_value"`
	SeqNum    int32     `gorm:"column:seq_num;not null" json:"seq_num"`
	Status    bool      `gorm:"column:status;not null;default:1;comment:1:enabled 2:disabled" json:"status"` // 1:enabled 2:disabled
	Remark    string    `gorm:"column:remark;not null" json:"remark"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName DictDatum's table name
func (*DictDatum) TableName() string {
	return TableNameDictDatum
}
