// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGovernanceChoice = "governance_choice"

// GovernanceChoice mapped from table <governance_choice>
type GovernanceChoice struct {
	ID         int64     `gorm:"column:id;primaryKey" json:"id"`
	ProposalID int64     `gorm:"column:proposal_id;not null" json:"proposal_id"`
	ItemName   string    `gorm:"column:item_name;not null" json:"item_name"`
	SeqNum     int32     `gorm:"column:seq_num;not null" json:"seq_num"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted  bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName GovernanceChoice's table name
func (*GovernanceChoice) TableName() string {
	return TableNameGovernanceChoice
}
