// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGovernanceSetting = "governance_setting"

// GovernanceSetting mapped from table <governance_setting>
type GovernanceSetting struct {
	ID                int64     `gorm:"column:id;primaryKey" json:"id"`
	StartupID         int64     `gorm:"column:startup_id;not null" json:"startup_id"`
	ComerID           int64     `gorm:"column:comer_id;not null" json:"comer_id"`
	VoteSymbol        string    `gorm:"column:vote_symbol;not null" json:"vote_symbol"`
	AllowMember       bool      `gorm:"column:allow_member;not null;comment:0:no  1:yes" json:"allow_member"` // 0:no  1:yes
	ProposalThreshold float64   `gorm:"column:proposal_threshold;not null" json:"proposal_threshold"`
	ProposalValidity  float64   `gorm:"column:proposal_validity;not null" json:"proposal_validity"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted         bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName GovernanceSetting's table name
func (*GovernanceSetting) TableName() string {
	return TableNameGovernanceSetting
}
