// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGovernanceStrategy = "governance_strategy"

// GovernanceStrategy mapped from table <governance_strategy>
type GovernanceStrategy struct {
	ID                   int32     `gorm:"column:id;primaryKey" json:"id"`
	SettingID            int64     `gorm:"column:setting_id;not null" json:"setting_id"`
	DictValue            string    `gorm:"column:dict_value;not null" json:"dict_value"`
	StrategyName         string    `gorm:"column:strategy_name;not null" json:"strategy_name"`
	ChainID              int64     `gorm:"column:chain_id;not null" json:"chain_id"`
	TokenContractAddress string    `gorm:"column:token_contract_address;not null" json:"token_contract_address"`
	VoteSymbol           string    `gorm:"column:vote_symbol;not null" json:"vote_symbol"`
	VoteDecimals         int32     `gorm:"column:vote_decimals;not null" json:"vote_decimals"`
	TokenMinBalance      float64   `gorm:"column:token_min_balance;not null" json:"token_min_balance"`
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted            bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName GovernanceStrategy's table name
func (*GovernanceStrategy) TableName() string {
	return TableNameGovernanceStrategy
}
