// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGovernanceAdmin = "governance_admin"

// GovernanceAdmin mapped from table <governance_admin>
type GovernanceAdmin struct {
	ID            int32     `gorm:"column:id;primaryKey" json:"id"`
	SettingID     int64     `gorm:"column:setting_id;not null" json:"setting_id"`
	WalletAddress string    `gorm:"column:wallet_address;not null" json:"wallet_address"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted     bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName GovernanceAdmin's table name
func (*GovernanceAdmin) TableName() string {
	return TableNameGovernanceAdmin
}
