// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImage = "image"

// Image mapped from table <image>
type Image struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	Category  string    `gorm:"column:category;not null" json:"category"`
	Name      string    `gorm:"column:name;not null;comment:name" json:"name"` // name
	URL       string    `gorm:"column:url;not null;comment:url" json:"url"`    // url
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted bool      `gorm:"column:is_deleted;not null;comment:Is Deleted" json:"is_deleted"` // Is Deleted
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
