// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePostUpdate = "post_update"

// PostUpdate mapped from table <post_update>
type PostUpdate struct {
	ID         int32     `gorm:"column:id;primaryKey" json:"id"`
	SourceType bool      `gorm:"column:source_type;not null" json:"source_type"`
	SourceID   int64     `gorm:"column:source_id;not null" json:"source_id"`
	ComerID    int64     `gorm:"column:comer_id;not null" json:"comer_id"`
	Content    string    `gorm:"column:content;not null" json:"content"`
	Timestamp  time.Time `gorm:"column:timestamp;not null;default:0000-00-00 00:00:00" json:"timestamp"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted  bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName PostUpdate's table name
func (*PostUpdate) TableName() string {
	return TableNamePostUpdate
}
