// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStartup = "startup"

// Startup mapped from table <startup>
type Startup struct {
	ID                   int64     `gorm:"column:id;primaryKey" json:"id"`
	ComerID              int64     `gorm:"column:comer_id;not null;comment:comer_id" json:"comer_id"`                   // comer_id
	Name                 string    `gorm:"column:name;not null;comment:name" json:"name"`                               // name
	Mode                 int32     `gorm:"column:mode;not null;comment:0:NONE, 1:ESG, 2:NGO, 3:DAO, 4:COM" json:"mode"` // 0:NONE, 1:ESG, 2:NGO, 3:DAO, 4:COM
	Logo                 string    `gorm:"column:logo;not null;comment:logo" json:"logo"`                               // logo
	Cover                string    `gorm:"column:cover;not null" json:"cover"`
	Mission              string    `gorm:"column:mission;not null;comment:logo" json:"mission"`                                                 // logo
	TokenContractAddress string    `gorm:"column:token_contract_address;not null;comment:token contract address" json:"token_contract_address"` // token contract address
	Overview             string    `gorm:"column:overview;not null;comment:overview" json:"overview"`                                           // overview
	TxHash               string    `gorm:"column:tx_hash;not null" json:"tx_hash"`
	OnChain              bool      `gorm:"column:on_chain;not null;comment:whether it is on the chain" json:"on_chain"` // whether it is on the chain
	Kyc                  string    `gorm:"column:kyc;not null;comment:KYC" json:"kyc"`                                  // KYC
	ContractAudit        string    `gorm:"column:contract_audit;not null;comment:contract audit" json:"contract_audit"` // contract audit
	Website              string    `gorm:"column:website;not null;comment:website" json:"website"`                      // website
	Discord              string    `gorm:"column:discord;not null;comment:discord" json:"discord"`                      // discord
	Twitter              string    `gorm:"column:twitter;not null;comment:twitter" json:"twitter"`                      // twitter
	Telegram             string    `gorm:"column:telegram;not null;comment:telegram" json:"telegram"`                   // telegram
	Docs                 string    `gorm:"column:docs;not null;comment:docs" json:"docs"`                               // docs
	Email                string    `gorm:"column:email;not null" json:"email"`
	Facebook             string    `gorm:"column:facebook;not null" json:"facebook"`
	Medium               string    `gorm:"column:medium;not null" json:"medium"`
	Linktree             string    `gorm:"column:linktree;not null" json:"linktree"`
	LaunchNetwork        int32     `gorm:"column:launch_network;not null;comment:chain id" json:"launch_network"`                                     // chain id
	TokenName            string    `gorm:"column:token_name;not null;comment:token name" json:"token_name"`                                           // token name
	TokenSymbol          string    `gorm:"column:token_symbol;not null;comment:token symbol" json:"token_symbol"`                                     // token symbol
	TotalSupply          int64     `gorm:"column:total_supply;not null;comment:total supply" json:"total_supply"`                                     // total supply
	PresaleStart         time.Time `gorm:"column:presale_start;not null;default:0000-00-00 00:00:00;comment:presale start date" json:"presale_start"` // presale start date
	PresaleEnd           time.Time `gorm:"column:presale_end;not null;default:0000-00-00 00:00:00;comment:presale end date" json:"presale_end"`       // presale end date
	LaunchDate           time.Time `gorm:"column:launch_date;not null;default:0000-00-00 00:00:00;comment:launch_date" json:"launch_date"`            // launch_date
	TabSequence          string    `gorm:"column:tab_sequence;not null" json:"tab_sequence"`
	CreatedAt            time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt            time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted            bool      `gorm:"column:is_deleted;not null;comment:Is Deleted" json:"is_deleted"` // Is Deleted
}

// TableName Startup's table name
func (*Startup) TableName() string {
	return TableNameStartup
}
