// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStartupTeamMemberRel = "startup_team_member_rel"

// StartupTeamMemberRel mapped from table <startup_team_member_rel>
type StartupTeamMemberRel struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	ComerID   int64     `gorm:"column:comer_id;not null;comment:comer_id" json:"comer_id"`       // comer_id
	StartupID int64     `gorm:"column:startup_id;not null;comment:startup_id" json:"startup_id"` // startup_id
	Position  string    `gorm:"column:position;not null;comment:title" json:"position"`          // title
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName StartupTeamMemberRel's table name
func (*StartupTeamMemberRel) TableName() string {
	return TableNameStartupTeamMemberRel
}
