// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStartupGroupMemberRel = "startup_group_member_rel"

// StartupGroupMemberRel mapped from table <startup_group_member_rel>
type StartupGroupMemberRel struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	ComerID   int64     `gorm:"column:comer_id;not null;comment:comer_id" json:"comer_id"`       // comer_id
	StartupID int64     `gorm:"column:startup_id;not null;comment:startup_id" json:"startup_id"` // startup_id
	GroupID   int64     `gorm:"column:group_id;not null;comment:group id" json:"group_id"`       // group id
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName StartupGroupMemberRel's table name
func (*StartupGroupMemberRel) TableName() string {
	return TableNameStartupGroupMemberRel
}
