// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTagTargetRel = "tag_target_rel"

// TagTargetRel mapped from table <tag_target_rel>
type TagTargetRel struct {
	ID        int64     `gorm:"column:id;primaryKey" json:"id"`
	Target    string    `gorm:"column:target;not null;comment:comerSkill,startup" json:"target"` // comerSkill,startup
	TargetID  int64     `gorm:"column:target_id;not null;comment:target id" json:"target_id"`    // target id
	TagID     int64     `gorm:"column:tag_id;not null;comment:skill id" json:"tag_id"`           // skill id
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TagTargetRel's table name
func (*TagTargetRel) TableName() string {
	return TableNameTagTargetRel
}
