// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransaction = "transaction"

// Transaction mapped from table <transaction>
type Transaction struct {
	ID         int64     `gorm:"column:id;primaryKey" json:"id"`
	ChainID    int64     `gorm:"column:chain_id;not null" json:"chain_id"`
	TxHash     string    `gorm:"column:tx_hash;not null" json:"tx_hash"`
	Timestamp  time.Time `gorm:"column:timestamp;not null;default:0000-00-00 00:00:00" json:"timestamp"`
	Status     bool      `gorm:"column:status;not null;comment:0:Pending 1:Success 2:Failure" json:"status"` // 0:Pending 1:Success 2:Failure
	SourceType bool      `gorm:"column:source_type;not null" json:"source_type"`
	SourceID   int64     `gorm:"column:source_id;not null" json:"source_id"`
	RetryTimes int32     `gorm:"column:retry_times;not null" json:"retry_times"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	IsDeleted  bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
