version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smart-route-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartroute
      POSTGRES_USER: smartroute
      POSTGRES_PASSWORD: 12345678
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smart-route-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartroute"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: smart-route-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-route-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  smart-route-network:
    driver: bridge 