// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateOrderReq struct {
	ProductId uint `json:"productId"`
	Count     uint `json:"count"`
}

type CreateOrderRes struct {
	OrderId uint `json:"orderId"`
}

type GetOrderDetailReq struct {
	OrderId uint `json:"orderId"`
}

type GetOrderDetailRes struct {
	OrderId   uint `json:"orderId"`
	ProductId uint `json:"productId"`
	Count     uint `json:"count"`
}
