// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type BaseResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type GetTokenInfoListReq struct {
	StartIndex uint64 `form:"startIndex,optional"`
	PageSize   uint64 `form:"pageSize,optional"`
}

type GetTokenInfoReq struct {
	Id uint64 `form:"id"`
}

type GetTokenInfoRes struct {
	Id     uint64 `json:"id"`
	Symbol string `json:"symbol"`
	Logo   string `json:"logo"`
}

type SearchReq struct {
	GetTokenInfoListReq
	Id      uint64 `form:"id,optional"`
	Symbol  string `form:"symbol,optional"`
	ChainId string `form:"chainId,optional"`
}
