// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateUserReq struct {
	Name string `json:"name"`
}

type CreateUserRes struct {
	UserId uint `json:"userId"`
}

type GetUserDetailReq struct {
	UserId uint `form:"userId"`
}

type GetUserDetailRes struct {
	UserId uint   `json:"userId"`
	Name   string `json:"name"`
}
