server:
  port: 8080

database:
  postgresql:
    host: localhost
    port: 5432
    user: postgres
    password: 12345678
    dbname: smart_route
    sslmode: disable
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 300

redis:
  host: localhost
  port: 6379
  password: "12345678"
  db: 0
  pool_size: 10

jwt:
  secret: "your-super-secret-jwt-key-change-in-production"
  expires_hours: 24 