server:
  port: 8080

database:
  postgresql:
    host: localhost
    port: 5433
    user: smartroute
    password: 12345678
    dbname: smartroute
    sslmode: disable
    max_open_conns: 25
    max_idle_conns: 5
    conn_max_lifetime: 300

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

jwt:
  secret: "your-super-secret-jwt-key-change-in-production"
  expires_hours: 24 