[jwt]
expire_time = 2592000
secret_key = ""

[env]
port = "8080"
version = "21"
protocol = "https"
task_duration = 2
task_extend_duration = 5
wss_timeout_duration = 20
domain_name = "dev-v2-backend.pledger.finance"

[threshold]
pledge_pool_token_threshold_bnb = "100000000000000000"

[email]
user_name=""
password = ""
host = "smtp.gmail.com"
port = "587"
from = "pledge beidge <test@gmail.com>"
subject = "Insufficient balance of bridge account"
to = ["xxx@outlook.com"]
cc = ["xx@gmail.com"]